// Edge-runtime safe — no dynamic imports, pure static record
// Maps legacy venue IDs to their canonical emirate + slug route segments

export const VENUE_SLUG_MAP: Record<string, { emirate: string; slug: string }> = {
  // Restaurants
  bagatelle: { emirate: 'dubai', slug: 'bagatelle' },
  verde: { emirate: 'dubai', slug: 'verde' },
  coucou: { emirate: 'dubai', slug: 'coucou' },
  amazonico: { emirate: 'dubai', slug: 'amazonico' },
  'il-gattopardo': { emirate: 'dubai', slug: 'il-gattopardo' },
  'bar-de-pres': { emirate: 'dubai', slug: 'bar-de-pres' },
  '1920': { emirate: 'dubai', slug: '1920' },
  nahate: { emirate: 'dubai', slug: 'nahate' },
  nobu: { emirate: 'dubai', slug: 'nobu' },
  'ling-ling': { emirate: 'dubai', slug: 'ling-ling' },
  'la-mar': { emirate: 'dubai', slug: 'la-mar' },
  hakkasan: { emirate: 'dubai', slug: 'hakkasan' },
  mambaella: { emirate: 'dubai', slug: 'mambaella' },
  woohoo: { emirate: 'dubai', slug: 'woohoo' },
  'ram-and-roll': { emirate: 'dubai', slug: 'ram-and-roll' },
  tang: { emirate: 'dubai', slug: 'tang' },
  nazcaa: { emirate: 'dubai', slug: 'nazcaa' },
  krasota: { emirate: 'dubai', slug: 'krasota' },
  salvaje: { emirate: 'dubai', slug: 'salvaje' },
  'villa-coconut': { emirate: 'dubai', slug: 'villa-coconut' },
  'shanghai-me': { emirate: 'dubai', slug: 'shanghai-me' },
  gal: { emirate: 'dubai', slug: 'gal' },
  urla: { emirate: 'dubai', slug: 'urla' },
  coya: { emirate: 'dubai', slug: 'coya' },
  amelia: { emirate: 'dubai', slug: 'amelia' },
  'ce-la-vi': { emirate: 'dubai', slug: 'ce-la-vi' },
  'sushi-samba': { emirate: 'dubai', slug: 'sushi-samba' },
  'la-nina': { emirate: 'dubai', slug: 'la-nina' },
  opa: { emirate: 'dubai', slug: 'opa' },
  clap: { emirate: 'dubai', slug: 'clap' },
  'sexy-fish': { emirate: 'dubai', slug: 'sexy-fish' },
  nammos: { emirate: 'dubai', slug: 'nammos' },
  jumeirah: { emirate: 'dubai', slug: 'jumeirah' },
  tattu: { emirate: 'dubai', slug: 'tattu' },

  // Beach Clubs
  'verde-beach': { emirate: 'dubai', slug: 'verde-beach' },
  'african-queen': { emirate: 'dubai', slug: 'african-queen' },
  sakhalin: { emirate: 'dubai', slug: 'sakhalin' },
  'gigi-beach': { emirate: 'dubai', slug: 'gigi-beach' },
  'baoli-beach': { emirate: 'dubai', slug: 'baoli-beach' },
  'ina-beach': { emirate: 'dubai', slug: 'ina-beach' },
  'maison-revka': { emirate: 'dubai', slug: 'maison-revka' },
  'nikki-beach': { emirate: 'dubai', slug: 'nikki-beach' },
  'nobu-beach': { emirate: 'dubai', slug: 'nobu-beach' },
  'casablanca-beach': { emirate: 'dubai', slug: 'casablanca-beach' },
  'drift-beach': { emirate: 'dubai', slug: 'drift-beach' },
  playa: { emirate: 'dubai', slug: 'playa' },
  'terra-solis': { emirate: 'dubai', slug: 'terra-solis' },
  'surf-beach': { emirate: 'dubai', slug: 'surf-beach' },
  gitano: { emirate: 'dubai', slug: 'gitano' },
  'bch-club': { emirate: 'dubai', slug: 'bch-club' },
  kyma: { emirate: 'dubai', slug: 'kyma' },
  'casa-amor': { emirate: 'dubai', slug: 'casa-amor' },
  'ninive-beach': { emirate: 'dubai', slug: 'ninive-beach' },
  'maison-de-la-plage': { emirate: 'dubai', slug: 'maison-de-la-plage' },
  'lucky-fish': { emirate: 'dubai', slug: 'lucky-fish' },
  'gallery-740': { emirate: 'dubai', slug: 'gallery-740' },
  'o-beach': { emirate: 'dubai', slug: 'o-beach' },
  'zetta-pool': { emirate: 'dubai', slug: 'zetta-pool' },

  // Night Clubs
  iris: { emirate: 'dubai', slug: 'iris' },
  epik: { emirate: 'dubai', slug: 'epik' },
  nyx: { emirate: 'dubai', slug: 'nyx' },
  'ly-la': { emirate: 'dubai', slug: 'ly-la' },
  'paraiso-rooftop': { emirate: 'dubai', slug: 'paraiso-rooftop' },
  'blume-lounge': { emirate: 'dubai', slug: 'blume-lounge' },
  'shanghai-me-nc': { emirate: 'dubai', slug: 'shanghai-me-nc' },
  rasputine: { emirate: 'dubai', slug: 'rasputine' },
  avenue: { emirate: 'dubai', slug: 'avenue' },
  ora: { emirate: 'dubai', slug: 'ora' },
  'secret-room': { emirate: 'dubai', slug: 'secret-room' },
  socialista: { emirate: 'dubai', slug: 'socialista' },
  'soho-garden': { emirate: 'dubai', slug: 'soho-garden' },
  code: { emirate: 'dubai', slug: 'code' },
  'babylon-nc': { emirate: 'dubai', slug: 'babylon-nc' },
  litt: { emirate: 'dubai', slug: 'litt' },
  ongaku: { emirate: 'dubai', slug: 'ongaku' },

  // Dining & Entertainment
  adaline: { emirate: 'dubai', slug: 'adaline' },
  aretha: { emirate: 'dubai', slug: 'aretha' },
  dream: { emirate: 'dubai', slug: 'dream' },
  gatsby: { emirate: 'dubai', slug: 'gatsby' },
  theater: { emirate: 'dubai', slug: 'theater' },
  billionaire: { emirate: 'dubai', slug: 'billionaire' },
  'babylon-de': { emirate: 'dubai', slug: 'babylon-de' },

  // Experiences
  'exp-platinum': { emirate: 'dubai', slug: 'exp-platinum' },
  'exp-skydive': { emirate: 'dubai', slug: 'exp-skydive' },
};
