-- ==========================================
-- DALC Seed Data
-- Run after schema.sql in Supabase SQL Editor
-- ==========================================
-- TIP: For bulk venue import, use the mockData.ts file
-- and the Supabase dashboard CSV import feature,
-- or run the generate-seed script.
-- ==========================================

-- Sample venues (subset — full data is in src/data/mockData.ts)
INSERT INTO public.venues (id, name, category, subcategory, location, area, vibe_tags, skills, price_tier, hero_image, gallery_images, description_short, description_long, highlights, recommend_score, is_featured, is_trending, trending_score, opening_hours, dress_code, booking_policy, best_time, who_its_for, status) VALUES
('nc-nyx', 'Nyx', 'nightlife', 'Hidden Club', 'DIFC', 'DIFC', ARRAY['Exclusive', 'Hidden', 'Greek'], ARRAY['NIGHTLIFE', 'SOCIALITE', 'LUXURY'], 4, 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?q=80&w=2529&auto=format&fit=crop', ARRAY['https://images.unsplash.com/photo-1514525253440-b393452e3726?q=80&w=2574&auto=format&fit=crop'], 'The secret club beneath Gaia.', 'Hidden behind a secret door in Gaia, Nyx is an exclusive, myths-inspired nightclub that hosts the city''s most elite crowd. No photos allowed.', ARRAY['Strict Privacy', 'Elite Crowd', 'Signature Design'], 98, true, true, 98, 'Thu-Sat: 11:00 PM - 4:00 AM', 'Glamorous', 'Invite only / Table booking.', 'Late Night', 'Social Elite', 'published'),

('nc-raspoutine', 'Raspoutine', 'nightlife', 'Parisian Club', 'DIFC', 'DIFC', ARRAY['Red Velvet', 'Parisian', 'Deep House'], ARRAY['NIGHTLIFE', 'SOCIALITE', 'LUXURY', 'CULTURAL'], 4, 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?q=80&w=2576&auto=format&fit=crop', ARRAY['https://images.unsplash.com/photo-1505236858219-8359eb29e329?q=80&w=2662&auto=format&fit=crop'], 'The legendary Parisian cabaret-club.', 'With its signature red velvet decor and alcoves, Raspoutine Dubai maintains the mystique of its Paris original. It''s a dinner-club that transforms into a deep house sanctuary.', ARRAY['Iconic Decor', 'Deep House', 'Intimate'], 95, true, true, 95, 'Tue-Sat: 9:00 PM - 3:00 AM', 'Glamorous', 'Strict selection.', 'Midnight', 'Global Jetsetters', 'published'),

('nc-soho-meydan', 'Soho Garden Meydan', 'nightlife', 'Nightlife Complex', 'Meydan', 'Meydan', ARRAY['Festival', 'Open Air', 'Techno'], ARRAY['NIGHTLIFE', 'SOCIALITE', 'ADVENTURE'], 3, 'https://images.unsplash.com/photo-1533174072545-e8d4aa97edf9?q=80&w=2574&auto=format&fit=crop', ARRAY['https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=2670&auto=format&fit=crop'], 'Dubai''s playground of house and techno.', 'A massive entertainment complex featuring multiple venues, gardens, and club rooms. Soho Garden is the go-to destination for big international DJ acts.', ARRAY['International DJs', 'Multiple Rooms', 'Outdoor Garden'], 96, true, true, 92, 'Daily: 8:00 PM - 4:00 AM', 'Club Ready', 'Walk-ins/Tables.', '11:00 PM', 'Music Fans, Groups', 'published'),

('r-ling-ling', 'Ling Ling', 'dining', 'Asian', 'Atlantis The Royal', 'Palm Jumeirah', ARRAY['Tokyo', 'Vibrant', 'DJ'], ARRAY['FOODIE', 'NIGHTLIFE', 'SOCIALITE', 'CULTURAL'], 4, 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=2670&auto=format&fit=crop', ARRAY['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=2574&auto=format&fit=crop'], 'Tokyo energy at Atlantis The Royal.', 'From the Hakkasan Group, Ling Ling is a vibrant Asian restaurant and late-night lounge known for its theatrical cocktails, Japanese-inspired cuisine, and DJ sets.', ARRAY['Japanese Cuisine', 'DJ Sets', 'Late Night Dining'], 97, false, true, 97, 'Daily: 7:00 PM - 3:00 AM', 'Smart Elegant', 'Reservation essential.', '10:00 PM', 'Couples, Night Owls', 'published'),

('r-hakkasan', 'Hakkasan', 'dining', 'Chinese', 'Atlantis The Palm', 'Palm Jumeirah', ARRAY['Michelin', 'Moody', 'Luxury'], ARRAY['FOODIE', 'LUXURY', 'NETWORKING'], 4, 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=2670&auto=format&fit=crop', ARRAY['https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=2574&auto=format&fit=crop'], 'Michelin-starred Cantonese cuisine.', 'The Dubai outpost of the Michelin-starred Cantonese restaurant. Dark, moody interiors meet exquisite dim sum and signature cocktails.', ARRAY['Michelin Star', 'Dim Sum', 'Signature Cocktails'], 96, false, true, 88, 'Daily: 6:00 PM - 1:00 AM', 'Smart Elegant', 'Reservation required.', 'Dinner Service', 'Business, Couples', 'published')

ON CONFLICT (id) DO NOTHING;
