export interface MapVenue {
  id: string;
  name: string;
  category: string;
  subcategory?: string;
  area: string;
  lat: number;
  lng: number;
  description: string;
  price_tier: number;
  hero_image: string;
  vibe_tags: string[];
}

/**
 * All DALC curated venues with precise Dubai GPS coordinates.
 * Coordinates are spread slightly within each district so markers
 * don't perfectly overlap on the 3D map.
 */
export const DALC_VENUES: MapVenue[] = [
  // ─── NIGHT CLUBS ────────────────────────────────────────────────────────────
  {
    id: 'nc-iris',
    name: 'Iris',
    category: 'nightlife',
    subcategory: 'Rooftop Lounge',
    area: 'Meydan',
    lat: 25.1612,
    lng: 55.3082,
    description: 'The ultimate rooftop escape at Meydan.',
    price_tier: 3,
    hero_image: 'https://images.unsplash.com/photo-1570570532251-5444b7d52df9?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Rooftop', 'Sunset', 'Live Music'],
  },
  {
    id: 'nc-epik',
    name: 'Epik',
    category: 'nightlife',
    subcategory: 'Superclub',
    area: 'Meydan',
    lat: 25.1608,
    lng: 55.3074,
    description: 'A futuristic nightlife odyssey.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1574391884720-385075902438?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Techno', 'Future', 'High Energy'],
  },
  {
    id: 'nc-nyx',
    name: 'Nyx',
    category: 'nightlife',
    subcategory: 'Hidden Club',
    area: 'DIFC',
    lat: 25.2172,
    lng: 55.2832,
    description: 'The secret club beneath Gaia.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Exclusive', 'Hidden', 'Greek'],
  },
  {
    id: 'nc-ly-la',
    name: 'Ly-La',
    category: 'nightlife',
    subcategory: 'Speakeasy',
    area: 'DIFC',
    lat: 25.2166,
    lng: 55.2840,
    description: 'A modern Bedouin lounge beneath Alaya.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1571867424488-4565932edb41?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Bedouin', 'House', 'Intimate'],
  },
  {
    id: 'nc-paraiso',
    name: 'Paraiso',
    category: 'nightlife',
    subcategory: 'Rooftop Club',
    area: 'DIFC',
    lat: 25.2181,
    lng: 55.2848,
    description: 'The vibrant rooftop of Amazonico.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1596228514170-69255653b47c?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Tropical', 'Rooftop', 'Latino'],
  },
  {
    id: 'nc-bund',
    name: 'Bund Lounge',
    category: 'nightlife',
    subcategory: 'Secret Bar',
    area: 'DIFC',
    lat: 25.2164,
    lng: 55.2858,
    description: 'A hidden gem inside Shanghai Me.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Shanghai 30s', 'Exclusive', 'Red'],
  },
  {
    id: 'nc-raspoutine',
    name: 'Raspoutine',
    category: 'nightlife',
    subcategory: 'Parisian Club',
    area: 'DIFC',
    lat: 25.2178,
    lng: 55.2824,
    description: 'The legendary Parisian cabaret-club.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Red Velvet', 'Parisian', 'Deep House'],
  },
  {
    id: 'nc-avenue',
    name: 'Avenue',
    category: 'nightlife',
    subcategory: 'Nightclub',
    area: 'Sheikh Zayed Road',
    lat: 25.2261,
    lng: 55.2835,
    description: "The pulse of Dubai's urban nightlife.",
    price_tier: 3,
    hero_image: 'https://images.unsplash.com/photo-1576085898323-218337e3e43c?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Urban', 'Hip Hop', 'Afrobeats'],
  },
  {
    id: 'nc-ora',
    name: 'Ora',
    category: 'nightlife',
    subcategory: 'Lounge Club',
    area: 'Business Bay',
    lat: 25.1843,
    lng: 55.2698,
    description: 'Opulence in Habtoor City.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1578736641330-3155e606cd40?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Opulent', 'Design', 'Lounge'],
  },
  {
    id: 'nc-secret-room',
    name: 'Secret Room',
    category: 'nightlife',
    subcategory: 'Underground Club',
    area: 'Downtown',
    lat: 25.2012,
    lng: 55.2765,
    description: 'Drive your supercar into the club.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1621693247912-c96695ad9636?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Underground', 'Exclusive', 'Hip Hop'],
  },
  {
    id: 'nc-socialista',
    name: 'Socialista',
    category: 'nightlife',
    subcategory: 'Cuban Lounge',
    area: 'DIFC',
    lat: 25.2170,
    lng: 55.2864,
    description: 'Havana nights in DIFC.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1534149638367-27b2a608112a?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Cuban', 'Colorful', 'Private'],
  },
  {
    id: 'nc-soho-meydan',
    name: 'Soho Garden Meydan',
    category: 'nightlife',
    subcategory: 'Nightlife Complex',
    area: 'Meydan',
    lat: 25.1617,
    lng: 55.3066,
    description: "Dubai's playground of house and techno.",
    price_tier: 3,
    hero_image: 'https://images.unsplash.com/photo-1533174072545-e8d4aa97edf9?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Festival', 'Open Air', 'Techno'],
  },
  {
    id: 'nc-soho-palm',
    name: 'Soho Garden Palm',
    category: 'nightlife',
    subcategory: 'Rooftop Club',
    area: 'Palm Jumeirah',
    lat: 25.1158,
    lng: 55.1388,
    description: 'Soho Garden vibes with Palm views.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1578474843222-675055771d89?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Rooftop', 'Views', 'House'],
  },
  {
    id: 'nc-code',
    name: 'Code',
    category: 'nightlife',
    subcategory: 'Techno Club',
    area: 'Meydan',
    lat: 25.1620,
    lng: 55.3058,
    description: 'Warehouse vibes and techno beats.',
    price_tier: 3,
    hero_image: 'https://images.unsplash.com/photo-1563841930606-67e26ce48657?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Industrial', 'Techno', 'Dark'],
  },
  {
    id: 'nc-babylon-club',
    name: 'Babylon Club',
    category: 'nightlife',
    subcategory: 'High Energy Club',
    area: 'DIFC',
    lat: 25.2159,
    lng: 55.2876,
    description: 'When dinner ends, the party begins.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Theatrical', 'Party', 'Luxury'],
  },
  {
    id: 'nc-litt',
    name: 'Litt',
    category: 'nightlife',
    subcategory: 'After Hours',
    area: 'DIFC',
    lat: 25.2185,
    lng: 55.2870,
    description: 'Where the night continues.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Afterparty', 'Intimate', 'Exclusive'],
  },
  {
    id: 'nc-ongaku',
    name: 'Ongaku',
    category: 'nightlife',
    subcategory: 'Hidden Bar',
    area: 'DIFC',
    lat: 25.2176,
    lng: 55.2854,
    description: 'The secret music room inside Clap.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1550966871-3ed3c47e2ce2?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Tokyo', 'Vinyl', 'Hidden'],
  },

  // ─── RESTAURANTS ─────────────────────────────────────────────────────────────
  {
    id: 'r-verde-fs',
    name: 'Verde',
    category: 'dining',
    subcategory: 'French Mediterranean',
    area: 'Jumeirah',
    lat: 25.0872,
    lng: 55.1380,
    description: 'Parisian chic meets Dubai luxury.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Party', 'Chic', 'Atmosphere'],
  },
  {
    id: 'r-coucou',
    name: 'CouCou',
    category: 'dining',
    subcategory: 'French Brasserie',
    area: 'Palm Jumeirah',
    lat: 25.1052,
    lng: 55.1410,
    description: 'Chic French brasserie on the Palm.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['French', 'Party', 'Chic'],
  },
  {
    id: 'r-il-gattopardo',
    name: 'Il Gattopardo',
    category: 'dining',
    subcategory: 'Italian Fine Dining',
    area: 'DIFC',
    lat: 25.2190,
    lng: 55.2808,
    description: 'Old-world Italian elegance in DIFC.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Italian', 'Elegant', 'Classic'],
  },
  {
    id: 'r-bar-de-pres',
    name: "Bar des Prés",
    category: 'dining',
    subcategory: 'French Bistro',
    area: 'DIFC',
    lat: 25.2193,
    lng: 55.2800,
    description: 'Cyril Lignac\'s iconic Parisian bistro lands in Dubai.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['French', 'Bistro', 'Chic'],
  },
  {
    id: 'r-1920',
    name: '1920',
    category: 'dining',
    subcategory: 'Modern Arabic',
    area: 'DIFC',
    lat: 25.2196,
    lng: 55.2816,
    description: 'A tribute to 1920s Lebanese heritage.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Arabic', 'Heritage', 'Intimate'],
  },
  {
    id: 'r-nahate',
    name: 'Nahate',
    category: 'dining',
    subcategory: 'Mediterranean',
    area: 'DIFC',
    lat: 25.2162,
    lng: 55.2878,
    description: 'Contemporary Mediterranean in the heart of DIFC.',
    price_tier: 3,
    hero_image: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Mediterranean', 'Vibrant', 'Social'],
  },
  {
    id: 'r-ling-ling',
    name: 'Ling Ling',
    category: 'dining',
    subcategory: 'Pan-Asian',
    area: 'Palm Jumeirah',
    lat: 25.1195,
    lng: 55.1448,
    description: "Hakkasan's party-dining concept at Mondrian.",
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Asian', 'Party', 'Rooftop'],
  },
  {
    id: 'r-la-mar',
    name: 'La Mar',
    category: 'dining',
    subcategory: 'Peruvian',
    area: 'Palm Jumeirah',
    lat: 25.0996,
    lng: 55.1432,
    description: 'Gastón Acurio\'s iconic Peruvian at the waterfront.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Peruvian', 'Waterfront', 'Ceviche'],
  },
  {
    id: 'r-hakkasan',
    name: 'Hakkasan',
    category: 'dining',
    subcategory: 'Modern Cantonese',
    area: 'Palm Jumeirah',
    lat: 25.1297,
    lng: 55.1198,
    description: 'World-renowned Cantonese fine dining at Atlantis.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Cantonese', 'Luxury', 'Fine Dining'],
  },
  {
    id: 'r-mamabello',
    name: 'Mama Bello',
    category: 'dining',
    subcategory: 'Italian Casual',
    area: 'Mall of the Emirates',
    lat: 25.1186,
    lng: 55.2003,
    description: 'Rustic Italian in the heart of Mall of the Emirates.',
    price_tier: 2,
    hero_image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Italian', 'Casual', 'Family'],
  },
  {
    id: 'r-ram-roll',
    name: 'Ram Roll',
    category: 'dining',
    subcategory: 'Japanese',
    area: 'Palm Jumeirah',
    lat: 25.1172,
    lng: 55.1397,
    description: 'Innovative Japanese rolls on the Palm.',
    price_tier: 3,
    hero_image: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Japanese', 'Creative', 'Trendy'],
  },
  {
    id: 'r-tang',
    name: 'Tang',
    category: 'dining',
    subcategory: 'Modern Chinese',
    area: 'Downtown',
    lat: 25.1983,
    lng: 55.2773,
    description: 'Contemporary Chinese cuisine in Downtown.',
    price_tier: 3,
    hero_image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Chinese', 'Modern', 'Social'],
  },
  {
    id: 'r-nazcaa',
    name: 'Nazcaa',
    category: 'dining',
    subcategory: 'Peruvian-Japanese',
    area: 'Downtown',
    lat: 25.2007,
    lng: 55.2762,
    description: 'Nikkei cuisine inspired by the Nazca civilisation.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Nikkei', 'Design Forward', 'Gold'],
  },
  {
    id: 'r-salvaje',
    name: 'Salvaje',
    category: 'dining',
    subcategory: 'Spanish',
    area: 'Downtown',
    lat: 25.1990,
    lng: 55.2753,
    description: 'Wild Spanish dining at Address Downtown.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Spanish', 'Party', 'High Energy'],
  },
  {
    id: 'r-villa-coconut',
    name: 'Villa Coconut',
    category: 'dining',
    subcategory: 'Tropical Fusion',
    area: 'DIFC',
    lat: 25.2155,
    lng: 55.2888,
    description: 'A tropical oasis hidden in DIFC.',
    price_tier: 3,
    hero_image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Tropical', 'Lush', 'Fun'],
  },
  {
    id: 'r-shanghai-me',
    name: 'Shanghai Me',
    category: 'dining',
    subcategory: 'Modern Chinese',
    area: 'DIFC',
    lat: 25.2163,
    lng: 55.2847,
    description: 'Iconic Shanghai-inspired dining and late night.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Chinese', 'Late Night', 'Iconic'],
  },
  {
    id: 'r-gaia',
    name: 'Gaia',
    category: 'dining',
    subcategory: 'Modern Greek',
    area: 'DIFC',
    lat: 25.2174,
    lng: 55.2834,
    description: 'Award-winning modern Greek in DIFC.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Greek', 'Award-Winning', 'Sophisticated'],
  },
  {
    id: 'r-urla',
    name: 'Urla',
    category: 'dining',
    subcategory: 'Turkish',
    area: 'Downtown',
    lat: 25.1978,
    lng: 55.2759,
    description: 'Refined Turkish cuisine with Aegean soul.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Turkish', 'Elegant', 'Heartfelt'],
  },
  {
    id: 'r-coya',
    name: 'Coya',
    category: 'dining',
    subcategory: 'Peruvian',
    area: 'Jumeirah',
    lat: 25.0868,
    lng: 55.1372,
    description: 'COYA Dubai — Peruvian vibrancy at its finest.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Peruvian', 'Vibrant', 'Party'],
  },
  {
    id: 'r-amelia',
    name: 'Amelia',
    category: 'dining',
    subcategory: 'French Mediterranean',
    area: 'Downtown',
    lat: 25.1965,
    lng: 55.2780,
    description: 'Warm French Mediterranean in Downtown Dubai.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['French', 'Romantic', 'Sunny'],
  },
  {
    id: 'r-ce-la-vi',
    name: 'Cé La Vi',
    category: 'dining',
    subcategory: 'Asian Fusion',
    area: 'Downtown',
    lat: 25.1975,
    lng: 55.2744,
    description: 'Rooftop sunset dining above Downtown.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Rooftop', 'Sunset', 'Asian Fusion'],
  },
  {
    id: 'r-sushisamba',
    name: 'SushiSamba',
    category: 'dining',
    subcategory: 'Japanese-Brazilian',
    area: 'Palm Jumeirah',
    lat: 25.0995,
    lng: 55.1438,
    description: 'The iconic Nikkei experience at The Palm.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Nikkei', 'Colorful', 'Rooftop'],
  },
  {
    id: 'r-la-nina',
    name: 'La Niña',
    category: 'dining',
    subcategory: 'Pan-Latin',
    area: 'DIFC',
    lat: 25.2157,
    lng: 55.2896,
    description: 'Bold Latin flavours and daring cocktails in DIFC.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Latin', 'Bold', 'Party'],
  },
  {
    id: 'r-opa',
    name: 'OPA',
    category: 'dining',
    subcategory: 'Greek',
    area: 'Sheikh Zayed Road',
    lat: 25.1960,
    lng: 55.2618,
    description: 'Festive Greek dining at Habtoor Palace.',
    price_tier: 3,
    hero_image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Greek', 'Festive', 'Live Music'],
  },
  {
    id: 'r-clap',
    name: 'Clap',
    category: 'dining',
    subcategory: 'Modern Japanese',
    area: 'DIFC',
    lat: 25.2177,
    lng: 55.2856,
    description: 'Japanese dining theatre in DIFC.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Japanese', 'Theatre', 'Cool'],
  },
  {
    id: 'r-sexy-fish',
    name: 'Sexy Fish',
    category: 'dining',
    subcategory: 'Asian Seafood',
    area: 'DIFC',
    lat: 25.2168,
    lng: 55.2868,
    description: 'Legendary London export — sexy Asian seafood in DIFC.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Showstopper', 'Seafood', 'Artful'],
  },
  {
    id: 'r-nammos',
    name: 'Nammos',
    category: 'dining',
    subcategory: 'Greek Seafood',
    area: 'Jumeirah',
    lat: 25.1858,
    lng: 55.2102,
    description: 'The Mykonos beachfront legend lands at Pearl Jumeirah.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Beach Club', 'Seafood', 'Mediterranean'],
  },
  {
    id: 'r-tattu',
    name: 'Tattu',
    category: 'dining',
    subcategory: 'Modern Chinese',
    area: 'Downtown',
    lat: 25.1963,
    lng: 55.2770,
    description: 'Visually stunning Chinese fine dining.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Chinese', 'Design', 'Instagram'],
  },
  {
    id: 'r-bagatelle',
    name: 'Bagatelle',
    category: 'dining',
    subcategory: 'French Mediterranean',
    area: 'Sheikh Zayed Road',
    lat: 25.2107,
    lng: 55.2732,
    description: 'Miami/NYC favourite — boisterous French dining in Dubai.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['French', 'Party', 'Fun'],
  },
  {
    id: 'r-amazonico',
    name: 'Amazonico',
    category: 'dining',
    subcategory: 'Brazilian-Latin',
    area: 'DIFC',
    lat: 25.2184,
    lng: 55.2844,
    description: 'Lush Amazon rainforest dining experience in DIFC.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Brazilian', 'Jungle', 'Vibrant'],
  },
  {
    id: 'r-nobu',
    name: 'Nobu',
    category: 'dining',
    subcategory: 'Japanese Fusion',
    area: 'Palm Jumeirah',
    lat: 25.1282,
    lng: 55.1196,
    description: 'The world-famous Nobu at Atlantis The Palm.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Japanese', 'Legendary', 'Luxurious'],
  },

  // ─── BEACH CLUBS ─────────────────────────────────────────────────────────────
  {
    id: 'bc-verde',
    name: 'Verde Beach',
    category: 'beach-clubs',
    subcategory: 'Beach Club',
    area: 'Umm Suqeim',
    lat: 25.1262,
    lng: 55.2075,
    description: 'Exclusive beach club at Jumeirah Al Naseem.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Beach', 'Luxury', 'Exclusive'],
  },
  {
    id: 'bc-nikki',
    name: 'Nikki Beach',
    category: 'beach-clubs',
    subcategory: 'Beach Club',
    area: 'Pearl Jumeirah',
    lat: 25.1855,
    lng: 55.2096,
    description: 'The global beach club icon at Pearl Jumeirah.',
    price_tier: 3,
    hero_image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Beach', 'Party', 'Global'],
  },
  {
    id: 'bc-kyma',
    name: 'Kyma Beach',
    category: 'beach-clubs',
    subcategory: 'Beach Club',
    area: 'Palm Jumeirah',
    lat: 25.1140,
    lng: 55.1402,
    description: 'Greek island vibes on the Palm Jumeirah.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Greek', 'Beach', 'Island Vibes'],
  },
  {
    id: 'bc-nobu',
    name: 'Nobu Beach Club',
    category: 'beach-clubs',
    subcategory: 'Beach Club',
    area: 'Palm Jumeirah',
    lat: 25.1288,
    lng: 55.1182,
    description: "Nobu's beach club at Atlantis The Palm.",
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Luxury', 'Beach', 'Japanese'],
  },

  // ─── DINING ENTERTAINMENT ────────────────────────────────────────────────────
  {
    id: 'de-billionaire',
    name: 'Billionaire',
    category: 'dining-entertainment',
    subcategory: 'Dinner Show',
    area: 'Business Bay',
    lat: 25.1847,
    lng: 55.2624,
    description: 'The most extravagant dinner show in Dubai.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1578474843222-675055771d89?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Dinner Show', 'Glamour', 'Entertainment'],
  },
  {
    id: 'de-babylon',
    name: 'Babylon',
    category: 'dining-entertainment',
    subcategory: 'Dinner Show',
    area: 'DIFC',
    lat: 25.2160,
    lng: 55.2878,
    description: 'A theatrical dinner and cabaret experience.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1578474843222-675055771d89?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Cabaret', 'Theatrical', 'Late Night'],
  },
  {
    id: 'de-josette',
    name: 'Josette',
    category: 'dining-entertainment',
    subcategory: 'French Brasserie Show',
    area: 'DIFC',
    lat: 25.2187,
    lng: 55.2812,
    description: 'Parisian dinner theatre with live acts.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1578474843222-675055771d89?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['French', 'Live Arts', 'Theatrical'],
  },
  {
    id: 'de-krasota',
    name: 'Krasota',
    category: 'dining-entertainment',
    subcategory: 'Immersive Dining',
    area: 'Downtown',
    lat: 25.2003,
    lng: 55.2750,
    description: 'Immersive culinary art installation.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1578474843222-675055771d89?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Immersive', 'Art', 'Multi-Sensory'],
  },
  {
    id: 'de-theater',
    name: 'Theater',
    category: 'dining-entertainment',
    subcategory: 'Dinner Show',
    area: 'Sheikh Zayed Road',
    lat: 25.2258,
    lng: 55.2829,
    description: 'A world-class theatrical dinner experience.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1578474843222-675055771d89?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Theatre', 'Dinner Show', 'Spectacular'],
  },

  // ─── EXPERIENCES ─────────────────────────────────────────────────────────────
  {
    id: 'exp-platinum',
    name: 'Platinum Heritage Desert Safari',
    category: 'experiences',
    subcategory: 'Desert',
    area: 'Desert',
    lat: 24.9200,
    lng: 55.6500,
    description: 'Luxury desert experience with vintage Land Rovers.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Desert', 'Safari', 'Heritage'],
  },
  {
    id: 'exp-skydive',
    name: 'Skydive Dubai',
    category: 'experiences',
    subcategory: 'Adventure',
    area: 'Dubai Marina',
    lat: 25.0720,
    lng: 55.1340,
    description: 'Tandem skydive over the iconic Palm Jumeirah.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1521673252305-82b17bec6c23?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Adrenaline', 'Sky', 'Iconic'],
  },
  {
    id: 'exp-balloon',
    name: 'Hot Air Balloon',
    category: 'experiences',
    subcategory: 'Adventure',
    area: 'Desert',
    lat: 24.9100,
    lng: 55.4800,
    description: 'Sunrise hot air balloon over the desert dunes.',
    price_tier: 3,
    hero_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Sunrise', 'Desert', 'Romantic'],
  },
  {
    id: 'exp-deepdive',
    name: 'DEEP DIVE Dubai',
    category: 'experiences',
    subcategory: 'Diving',
    area: 'Nad Al Sheba',
    lat: 25.1542,
    lng: 55.3102,
    description: 'The world\'s deepest swimming pool — 60m.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1559825481-12a05cc00344?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Diving', 'World Record', 'Unique'],
  },
  {
    id: 'exp-yacht',
    name: 'Private Yacht Charter',
    category: 'experiences',
    subcategory: 'Yacht',
    area: 'Dubai Marina',
    lat: 25.0772,
    lng: 55.1375,
    description: 'Private yacht charter around the Palm and Marina.',
    price_tier: 4,
    hero_image: 'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?q=80&w=600&auto=format&fit=crop',
    vibe_tags: ['Luxury', 'Sea', 'Private'],
  },
];

export const VENUE_CATEGORIES = [
  { id: 'all',                  label: 'All Venues',         color: '#C8A46B' },
  { id: 'nightlife',            label: 'Nightlife',          color: '#8B5CF6' },
  { id: 'dining',               label: 'Dining',             color: '#F59E0B' },
  { id: 'beach-clubs',          label: 'Beach Clubs',        color: '#06B6D4' },
  { id: 'dining-entertainment', label: 'Entertainment',      color: '#EC4899' },
  { id: 'experiences',          label: 'Experiences',        color: '#10B981' },
];
