export const economyCars = [
  {
    id: "economy-nissan-sunny-2023",
    brand: "Nissan",
    model: "Sunny",
    year: 2023,
    price: 70,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/nissan-sunny-2023.jpg",
  },
  {
    id: "economy-nissan-sunny-2024",
    brand: "Nissan",
    model: "Sunny",
    year: 2024,
    price: 75,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/nissan-sunny-2024.jpg",
  },
  {
    id: "economy-nissan-sunny-2025",
    brand: "Nissan",
    model: "Sunny",
    year: 2025,
    price: 85,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/nissan-sunny-2025.jpg",
  },
  {
    id: "economy-toyota-yaris-2023",
    brand: "Toyota",
    model: "Yaris",
    year: 2023,
    price: 80,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/toyota-yaris-2023.jpg",
  },
  {
    id: "economy-toyota-yaris-2024",
    brand: "Toyota",
    model: "Yaris",
    year: 2024,
    price: 85,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/toyota-yaris-2024.jpg",
  },
  {
    id: "economy-toyota-yaris-2025",
    brand: "Toyota",
    model: "Yaris",
    year: 2025,
    price: 95,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/toyota-yaris-2025.jpg",
  },
  {
    id: "economy-kia-picanto-2023",
    brand: "Kia",
    model: "Picanto",
    year: 2023,
    price: 65,
    fuel_type: "Petrol",
    seats: 4,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/kia-picanto-2023.jpg",
  },
  {
    id: "economy-kia-picanto-2024",
    brand: "Kia",
    model: "Picanto",
    year: 2024,
    price: 70,
    fuel_type: "Petrol",
    seats: 4,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/kia-picanto-2024.jpg",
  },
  {
    id: "economy-kia-picanto-2025",
    brand: "Kia",
    model: "Picanto",
    year: 2025,
    price: 80,
    fuel_type: "Petrol",
    seats: 4,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/kia-picanto-2025.jpg",
  },
  {
    id: "economy-hyundai-accent-2023",
    brand: "Hyundai",
    model: "Accent",
    year: 2023,
    price: 75,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/hyundai-accent-2023.jpg",
  },
  {
    id: "economy-hyundai-accent-2024",
    brand: "Hyundai",
    model: "Accent",
    year: 2024,
    price: 80,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/hyundai-accent-2024.jpg",
  },
  {
    id: "economy-hyundai-accent-2025",
    brand: "Hyundai",
    model: "Accent",
    year: 2025,
    price: 90,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/hyundai-accent-2025.jpg",
  },
  {
    id: "economy-mitsubishi-attrage-2023",
    brand: "Mitsubishi",
    model: "Attrage",
    year: 2023,
    price: 70,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/mitsubishi-attrage-2023.jpg",
  },
  {
    id: "economy-mitsubishi-attrage-2024",
    brand: "Mitsubishi",
    model: "Attrage",
    year: 2024,
    price: 75,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/mitsubishi-attrage-2024.jpg",
  },
  {
    id: "economy-mitsubishi-attrage-2025",
    brand: "Mitsubishi",
    model: "Attrage",
    year: 2025,
    price: 85,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/mitsubishi-attrage-2025.jpg",
  },
  {
    id: "economy-chevrolet-spark-2023",
    brand: "Chevrolet",
    model: "Spark",
    year: 2023,
    price: 65,
    fuel_type: "Petrol",
    seats: 4,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/chevrolet-spark-2023.jpg",
  },
  {
    id: "economy-chevrolet-spark-2024",
    brand: "Chevrolet",
    model: "Spark",
    year: 2024,
    price: 70,
    fuel_type: "Petrol",
    seats: 4,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/chevrolet-spark-2024.jpg",
  },
  {
    id: "economy-chevrolet-spark-2025",
    brand: "Chevrolet",
    model: "Spark",
    year: 2025,
    price: 80,
    fuel_type: "Petrol",
    seats: 4,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/chevrolet-spark-2025.jpg",
  },
  {
    id: "economy-renault-symbol-2024",
    brand: "Renault",
    model: "Symbol",
    year: 2024,
    price: 75,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/renault-symbol-2024.jpg",
  },
  {
    id: "economy-suzuki-ciaz-2025",
    brand: "Suzuki",
    model: "Ciaz",
    year: 2025,
    price: 90,
    fuel_type: "Petrol",
    seats: 5,
    category: "economy",
    transmission: "Automatic",
    image_url: "/cars/suzuki-ciaz-2025.jpg",
  },
];