-- Activities
INSERT INTO public.activities (vendor_id, category_id, slug, name, description_short, description_long, highlights, vibe_tags, service_type, duration_minutes, max_capacity, location, area, venue_name, age_minimum, dress_code, requirements, included, excluded, is_featured, is_trending, trending_score, booking_count, status) VALUES
('a0000000-0000-0000-0000-000000000009', (SELECT id FROM public.activity_categories WHERE slug='rooftop-lounges' LIMIT 1), 'aura-skypool-sunset-session', 'Aura Skypool Lounge — Sunset Session', 'The world''s highest 360 infinity pool with panoramic views of the Palm Jumeirah.', 'Experience the iconic Aura Skypool, suspended 200 meters in the air on the 50th floor of the Palm Tower.', ARRAY['360 infinity pool access','Palm Jumeirah skyline views','Premium sun lounger','Welcome champagne cocktail'], ARRAY['Luxury','Views','Instagram-worthy','Romantic'], 'recurring', 240, 120, 'Dubai', 'Palm Jumeirah', 'Aura Skypool', 21, 'Smart casual. Swimwear acceptable with cover-up.', ARRAY['Valid ID','Advance booking required'], ARRAY['Pool access','Sun lounger','Welcome drink','Towel service'], ARRAY['Food and beverages','Spa treatments','Transportation'], true, true, 98, 1247, 'published')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.activities (vendor_id, category_id, slug, name, description_short, description_long, highlights, vibe_tags, service_type, duration_minutes, max_capacity, location, area, venue_name, age_minimum, dress_code, requirements, included, excluded, is_featured, is_trending, trending_score, booking_count, status) VALUES
('a0000000-0000-0000-0000-000000000008', (SELECT id FROM public.activity_categories WHERE slug='clubs' LIMIT 1), 'white-dubai-vip-table', 'WHITE Dubai — VIP Table Experience', 'Dubai''s ultimate rooftop nightclub with world-class DJs and skyline views.', 'WHITE Dubai is an award-winning outdoor rooftop nightclub at Meydan Racecourse Grandstand.', ARRAY['VIP skip-the-line entry','Private table with premium location','Bottle service included','World-class DJ performances'], ARRAY['Party','High-energy','Celebrity hotspot','Luxury'], 'recurring', 300, 400, 'Dubai', 'Meydan', 'WHITE Dubai', 21, 'Smart elegant. No sportswear or flip-flops.', ARRAY['Valid ID or passport','Advance reservation required'], ARRAY['VIP entry','Private table','Bottle service','Mixers'], ARRAY['Additional beverages','Food','Transportation'], true, true, 95, 2156, 'published')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.activities (vendor_id, category_id, slug, name, description_short, description_long, highlights, vibe_tags, service_type, duration_minutes, max_capacity, location, area, age_minimum, requirements, included, excluded, is_featured, is_trending, trending_score, booking_count, status) VALUES
('a0000000-0000-0000-0000-000000000001', (SELECT id FROM public.activity_categories WHERE slug='desert-safari' LIMIT 1), 'platinum-desert-safari-dinner', 'Platinum Desert Safari and Dinner', 'Luxury desert safari with wildlife drive, falcon show, and gourmet dinner under the stars.', 'Experience the Dubai Desert Conservation Reserve in ultimate luxury.', ARRAY['Private Range Rover wildlife drive','Interactive falcon demonstration','6-course gourmet dinner','Traditional live entertainment'], ARRAY['Adventure','Luxury','Nature','Authentic'], 'recurring', 360, 40, 'Dubai Desert Conservation Reserve', 'Lahbab', 5, ARRAY['Comfortable clothing recommended','Hotel pickup included'], ARRAY['Hotel pickup/drop-off','Wildlife drive','Falcon show','Camel ride','Dinner','Entertainment'], ARRAY['Alcoholic beverages','Personal expenses','Gratuities'], true, true, 92, 1847, 'published')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.activities (vendor_id, category_id, slug, name, description_short, description_long, highlights, vibe_tags, service_type, duration_minutes, max_capacity, location, area, venue_name, age_minimum, requirements, included, excluded, is_featured, is_trending, trending_score, booking_count, status) VALUES
('a0000000-0000-0000-0000-000000000002', (SELECT id FROM public.activity_categories WHERE slug='skydiving' LIMIT 1), 'skydive-dubai-tandem-palm', 'Skydive Dubai — Tandem Palm Jump', 'The ultimate adrenaline rush — tandem skydive over the iconic Palm Jumeirah.', 'Jump from 13,000 feet with a certified instructor and freefall at 120mph.', ARRAY['Tandem jump from 13,000 feet','60-second freefall experience','Views of Palm Jumeirah and Burj Al Arab','Professional photos and video included'], ARRAY['Adrenaline','Bucket-list','Extreme','Unforgettable'], 'recurring', 180, 80, 'Dubai', 'Al Seyahi Street', 'Skydive Dubai', 18, ARRAY['Weight limit: 100kg max','Valid ID required','Good health condition'], ARRAY['Tandem jump','All equipment','Training briefing','Photos and video','Certificate'], ARRAY['Insurance','Transportation','Additional photos'], true, true, 96, 3421, 'published')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.activities (vendor_id, category_id, slug, name, description_short, description_long, highlights, vibe_tags, service_type, duration_minutes, max_capacity, location, area, venue_name, age_minimum, dress_code, requirements, included, excluded, is_featured, is_trending, trending_score, booking_count, status) VALUES
('a0000000-0000-0000-0000-000000000007', (SELECT id FROM public.activity_categories WHERE slug='fine-dining' LIMIT 1), 'tresind-studio-chefs-table', 'Tresind Studio — Chef''s Table Experience', 'Intimate 20-course progressive Indian dining at the Chef''s Table.', 'Tresind Studio is Dubai''s most celebrated progressive Indian restaurant, holding two Michelin stars.', ARRAY['20-course progressive tasting menu','Front-row kitchen views','Personal interaction with Chef','Wine pairing available'], ARRAY['Fine Dining','Michelin-starred','Intimate','Culinary Art'], 'recurring', 240, 12, 'Dubai', 'Palm Jumeirah', 'Tresind Studio', 12, 'Smart elegant', ARRAY['Advance booking essential','Dietary requirements must be advised'], ARRAY['20-course tasting menu','Welcome cocktail','Coffee/tea'], ARRAY['Wine pairing (optional)','Additional beverages','Gratuities'], true, true, 94, 892, 'published')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.activities (vendor_id, category_id, slug, name, description_short, description_long, highlights, vibe_tags, service_type, duration_minutes, max_capacity, location, area, venue_name, age_minimum, requirements, included, excluded, is_featured, is_trending, trending_score, booking_count, status) VALUES
('a0000000-0000-0000-0000-000000000004', (SELECT id FROM public.activity_categories WHERE slug='scuba-diving' LIMIT 1), 'atlantis-dive-shark-safari', 'Atlantis Dive — Shark Safari Experience', 'Dive among sharks, rays, and 65,000 marine animals at Atlantis The Palm.', 'The Shark Safari uses specialized helmets for underwater walking. No diving certification required.', ARRAY['Walk underwater in shark tank','No diving certification needed','Professional underwater photos','Marine life education session'], ARRAY['Underwater','Adventure','Family-friendly','Unique'], 'recurring', 120, 12, 'Dubai', 'Palm Jumeirah', 'Atlantis The Palm', 8, ARRAY['Good health condition','No diving experience required'], ARRAY['All equipment','Safety briefing','Underwater walk','Photos'], ARRAY['Wetsuit rental','Additional photos','Aquarium entry'], true, true, 89, 1567, 'published')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.activities (vendor_id, category_id, slug, name, description_short, description_long, highlights, vibe_tags, service_type, duration_minutes, max_capacity, location, area, venue_name, age_minimum, requirements, included, excluded, is_featured, is_trending, trending_score, booking_count, status) VALUES
('a0000000-0000-0000-0000-000000000003', (SELECT id FROM public.activity_categories WHERE slug='helicopter-tour' LIMIT 1), 'helidubai-iconic-tour', 'HeliDubai — Iconic Tour (22 min)', 'Breathtaking helicopter tour over Dubai''s most iconic landmarks.', 'See Dubai from a whole new perspective with this 22-minute helicopter tour.', ARRAY['22-minute aerial tour','Views of Burj Khalifa and Palm Jumeirah','Luxury Airbus H130 helicopter','Live commentary from pilot'], ARRAY['Views','Luxury','Photography','Bucket-list'], 'recurring', 60, 25, 'Dubai', 'Dubai Police Academy', 'HeliDubai', 2, ARRAY['Valid ID required','Weight limit applies'], ARRAY['22-min helicopter tour','Safety briefing','Live commentary'], ARRAY['Transportation','Photos (available for purchase)','Insurance'], true, true, 91, 2134, 'published')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.activities (vendor_id, category_id, slug, name, description_short, description_long, highlights, vibe_tags, service_type, duration_minutes, max_capacity, location, area, venue_name, age_minimum, dress_code, requirements, included, excluded, is_featured, is_trending, trending_score, booking_count, status) VALUES
('a0000000-0000-0000-0000-000000000005', (SELECT id FROM public.activity_categories WHERE slug='spa-resort' LIMIT 1), 'talise-ottoman-royal-hammam', 'Talise Ottoman Spa — Royal Hammam Ritual', 'Luxurious Turkish hammam experience in Dubai''s largest spa.', 'Immerse yourself in centuries-old Ottoman bathing traditions at Talise Ottoman Spa.', ARRAY['3-hour royal hammam ritual','Marble hamam chamber','Full body exfoliation and foam massage','Access to spa facilities'], ARRAY['Relaxation','Luxury','Traditional','Rejuvenating'], 'recurring', 180, 20, 'Dubai', 'Jumeirah Zabeel Saray', 'Talise Ottoman Spa', 16, 'Spa robes provided', ARRAY['Advance booking recommended','Arrive 15 minutes early'], ARRAY['Hammam ritual','Spa access','Towels','Slippers','Refreshments'], ARRAY['Additional treatments','Products','Gratuities'], true, false, 78, 743, 'published')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.activities (vendor_id, category_id, slug, name, description_short, description_long, highlights, vibe_tags, service_type, duration_minutes, max_capacity, location, area, venue_name, age_minimum, dress_code, requirements, included, excluded, is_featured, is_trending, trending_score, booking_count, status) VALUES
('a0000000-0000-0000-0000-000000000001', (SELECT id FROM public.activity_categories WHERE slug='heritage-walk' LIMIT 1), 'alfahidi-old-dubai-walking-tour', 'Al Fahidi Historical — Old Dubai Walking Tour', 'Discover the historic heart of Dubai on this guided heritage walk through Al Fahidi.', 'Step back in time and explore Dubai''s oldest neighborhood, Al Fahidi Historical District.', ARRAY['Guided heritage walk','Coffee Museum visit','Traditional abra boat ride','Gold and Spice Souk exploration'], ARRAY['Cultural','Educational','Authentic','Photography'], 'recurring', 180, 16, 'Dubai', 'Bur Dubai', 'Al Fahidi Historical District', 0, 'Modest dress recommended', ARRAY['Comfortable walking shoes','Sun protection'], ARRAY['Professional guide','Abra ride','Water','Coffee tasting','Souk visits'], ARRAY['Meals','Personal purchases','Gratuities'], false, false, 72, 428, 'published')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.activities (vendor_id, category_id, slug, name, description_short, description_long, highlights, vibe_tags, service_type, duration_minutes, max_capacity, location, area, venue_name, age_minimum, requirements, included, excluded, is_featured, is_trending, trending_score, booking_count, status) VALUES
('a0000000-0000-0000-0000-000000000001', (SELECT id FROM public.activity_categories WHERE slug='water-car' LIMIT 1), 'jetcar-drive-on-water', 'Jetcar — Drive on Water', 'The world''s first water car — drive a jet-powered supercar across the Arabian Gulf.', 'Built to resemble a sports car but powered by a marine jet engine, it lets you drive on water at thrilling speeds.', ARRAY['World''s first water car','Jet-powered supercar body','No license required','Dubai Marina coastline route'], ARRAY['Unique','Adrenaline','Instagram','VIP','One-of-a-kind'], 'on_demand', 20, 3, 'Dubai', 'Dubai Marina', 'DALC Water Sports', 16, ARRAY['Valid ID','Brief orientation included'], ARRAY['Jetcar rental','Life jacket','Orientation session','Fuel'], ARRAY['Photos/video','Insurance','Transportation'], true, true, 95, 423, 'published')
ON CONFLICT (slug) DO NOTHING;;
